name: Test your repo manifest repository

on:
  workflow_dispatch:
    inputs:
      LOCAL_MANIFEST_URL:
        description: 'LOCAL_MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/sounddrill31/local_manifests'
      LOCAL_MANIFEST_BRANCH:
        description: 'LOCAL_MANIFEST_BRANCH'
        required: true
        default: 'lineage-oxygen'
      ROM_MANIFEST_URL:
        description: 'MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/LineageOS/android'
      ROM_MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'lineage-20.0'
      CHOICE:
        type: choice
        description: 'Which would you like to test?'
        options:
        - ROM_MANIFEST
        - LOCAL_MANIFEST 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core python3-pip wget
          wget https://storage.googleapis.com/git-repo-downloads/repo && sudo mv repo /usr/bin/repo && sudo chmod a+x /usr/bin/repo
      - name: Initialize and Sync Repo for Manifest
        run: |
          rm -rf workspace
          mkdir workspace
          cd workspace
          echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          
                  rm -rf .repo/local_manifests &&
                  repo init --depth=1 -u https://github.com/LineageOS/android -b lineage-22.2 --git-lfs &&
            git clone https://github.com/LineageOS/android_device_samsung_a71 -b lineage-22.2 device/samsung/a71
            git clone https://github.com/LineageOS/android_device_samsung_a71-common -b lineage-22.2 device/samsung/a71-common
              git clone https://github.com/LineageOS/android_kernel_samsung_a71 -b lineage-22.2 kernel/samsung/a71
              git clone https://github.com/TheMuppets/proprietary_vendor_samsung_a71 -b lineage-22.2 vendor/samsung/a71
                  git clone https://github.com/TheMuppets/proprietary_vendor_samsung_a71-common -b lineage-22.2 vendor/samsung/a71-common 
            git clone https://github.com/LineageOS/android_hardware_qcom-caf_common -b lineage-22.2 hardware/qcom-caf/common
            git clone https://github.com/LineageOS/android_device_qcom_sepolicy-b lineage-22.2 device/qcom/sepolicy_vndr
              git clone https://github.com/LineageOS/android_hardware_samsung -b lineage-22.2 hardware/samsung

              repo sync --force-sync
           source build/envsetup.sh
                lunch lineage_a71-bp1a-userdebug
              mka bacon
        timeout-minutes: 10
    strategy:
        fail-fast: true
